### ISSUE TITLE
No module named 'os_tools.file_handler'

### ISSUE THREAD

**Issue by sqralhashimi** [osfunapps/os_android_apk_builder-py#1]
Hello

i get issue No module named 'os_tools.file_handler' although i have the os_tools install via pip but get the same error. how to resolve it please

**Comment by osfunapps** [comment]
Hey,

A lot of things have been changed. Please read the readme again and run:
`pip install os-android-apk-builder --upgrade`

**Comment by sqralhashimi** [comment]
Superb, thank you and great tool.
