### ISSUE TITLE
Please dont abandon this project

### ISSUE THREAD

**Issue by ustudio-ml** [osfunapps/os_android_apk_builder-py#3]
This is really great project, keep it upgrade please. There are so many bugs. Please dont abandoned it

**Comment by osfunapps** [comment]
What bugs did you find?

**Comment by ustudio-ml** [comment]
Hmmm..Why I can't install using pip install os-android-apk-builder?

**Comment by osfunapps** [comment]
Have you tried pip3 install?

**Comment by ustudio-ml** [comment]
Now I can

**Comment by ustudio-ml** [comment]
How about this one :
NameError: name 'KeyStoreProperties' is not defined

**Comment by osfunapps** [comment]
Please copy here the code you're trying to run
